server:
    port: 8080
    context-path: /sbarnacle/studious-spoon
    servlet:
        contextPath: /sbarnacle/studious-spoon

spring:
   dataSource:
        driverClassName: 'org.postgresql.Driver'
        password: 'sbarnacle'
        sql-script-encoding: UTF-8
        url: 'jdbc:postgresql://192.168.100.141:32671/sbarnacle'
        #'jdbc:postgresql://postgres-sbrncl-svc.sbarnacle.svc.cluster.local:5432/sbarnacle'
        # set spring.dataSource.url=jdbc:postgresql://192.168.100.141:32671/sbarnacle
        username: 'sbarnacle'
   jpa:
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults:
                        false
        databasePlatform: 'org.hibernate.dialect.PostgreSQLDialect'
        showSql: true
        hibernate:
           ddl-auto:
              update
   devtools:
      restart:
         enabled:
            false

                    
app:
    jwtExpirationInMs:
        604800000
    jwtSecret:
        sbarnacle-secret-auth@secret-key
    jwt_token_rca_public_key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhYUpzh/qPZMdXkN9Ybee
        ZHBvoILIDQijVJh2lu9Lr90OxXFTe6cf9+bQOrhYop9jI1iG7atr2KHpFXlndDEQ
        DIuVbqTRAV3jrrb+N/sUrCeBesmgNMQwlCRcgU8+BrtZqqx2DTLWYqDkS6m3XgQk
        y/+V/qIn70U/b0tf0sAdClDmrIvMHZ0xKxmidABow4t4yzxc+fNfSy5ArzMdJabv
        +2Rdheb3JuyYqCXHOP2kG9vvaLT0HSmLgqqJ4/T2FX3t0MqzLO3W5U3a/bTiagtO
        3z8aXPTBZffBCi9gNXV5lpIASXTW8rU7brlVrxsiGcVJBUpX20k0Uo3BpBSNEp5H
        YwIDAQAB
        -----END PUBLIC KEY-----

management:
   security:

   # https://github.com/spring-projects/spring-boot/blob/v2.1.3.RELEASE/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/endpoint/web/CorsEndpointProperties.java
   endpoints:
      web:
         cors:
            allowed-origins: 
               "*"
            allowed-methods:
               "GET, POST, PUT, DELETE, OPTION"


