apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose-kafka.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: zoo1
    app: zoo1
  name: zoo1
  namespace: sbarnacle-kafka
spec:
  #type: NodePort
  clusterIP: None
  ports:
  - name: client
    port: 2181
    targetPort: 2181
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  selector:
    app: zoo1


