apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluffy-invention
  namespace: sbarnacle
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable during the rolling update
  selector:
    matchLabels:
      app: fluffy-invention
  template:
    metadata:
      labels:
        app: fluffy-invention
    spec:
      containers:
      - name: fluffy-invention
        image: myregistrydomain.com:5000/sbarnacle/fluffy-invention:<BUILD_TAG>
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "30m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 20
          httpGet:
            path: /sbarnacle/fluffy-invention/api/ping/ping
            port: 8080
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 120
          httpGet:
            path: /sbarnacle/fluffy-invention/api/ping/ping
            port: 8080
        env:
        - name: "spring.kafka.bootstrap-servers"
          value: "kafka1-0.kafka1.sbarnacle-kafka.svc.cluster.local:9094"
        - name: "spring.kafka.consumer.group-id"
          value: "fluffy-invention-test2-consumers"
        - name: "app.cloudkarafka.topic"
          value: "fluffy-invention-test2-default"
        - name: "app.jwtSecret"
          value: "sbarnacle-secret-auth@secret-key"
        - name: "app.jwt_token_rca_public_key"
          value: |
                  -----BEGIN PUBLIC KEY-----
                  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhYUpzh/qPZMdXkN9Ybee
                  ZHBvoILIDQijVJh2lu9Lr90OxXFTe6cf9+bQOrhYop9jI1iG7atr2KHpFXlndDEQ
                  DIuVbqTRAV3jrrb+N/sUrCeBesmgNMQwlCRcgU8+BrtZqqx2DTLWYqDkS6m3XgQk
                  y/+V/qIn70U/b0tf0sAdClDmrIvMHZ0xKxmidABow4t4yzxc+fNfSy5ArzMdJabv
                  +2Rdheb3JuyYqCXHOP2kG9vvaLT0HSmLgqqJ4/T2FX3t0MqzLO3W5U3a/bTiagtO
                  3z8aXPTBZffBCi9gNXV5lpIASXTW8rU7brlVrxsiGcVJBUpX20k0Uo3BpBSNEp5H
                  YwIDAQAB
                  -----END PUBLIC KEY-----
          
      imagePullSecrets:
        - name: sbarnacle-docker-reg
---
apiVersion: v1
kind: Service
metadata:
  name: fluffy-invention-svc
  namespace: sbarnacle
  labels:
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: fluffy-invention
