# kubectl get  configmaps  -n kube-system coredns  --export -o yaml > coredns-config.yaml
# kubectl edit configmap coredns -n kube-system
# https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
#
# 192.168.100.141 myregistrydomain.com - docker registry
---
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    myregistrydomain.com:53 {
        errors
        cache 30
        proxy . 192.168.100.141
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: coredns
  namespace: kube-system
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
