FROM openjdk:11-slim
ADD /build/libs/studious-spoon-0.0.1-SNAPSHOT.jar studious-spoon.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "studious-spoon.jar"]





#
# chmod +x gradlew
# ./gradlew clean package
#
# sudo docker build -t sbarnacle/studious-spoon:1.0 .
# sudo docker tag sbarnacle/studious-spoon:1.0 myregistrydomain.com:5000/sbarnacle/studious-spoon:1.0
# sudo docker push myregistrydomain.com:5000/sbarnacle/studious-spoon:1.0




