---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gogs
  namespace: git-gogs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gogs
    spec:
      containers:
      - resources:
        name: gogs
        image: gogs/gogs:latest
        ports:
        - name: gogs-port
          containerPort: 3000
        volumeMounts:
        - mountPath: /data
          name: data
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gogs-claim0
     # nodeSelector:
     #   name: yv84.u2
---
apiVersion: v1
kind: Service
metadata:
  name: gogs
  namespace: git-gogs
  labels:
    name: gogs
spec:
  ports:
  - name: "port3000"
    port: 3000
    targetPort: 3000
    nodePort: 30130
  selector:
    name: gogs
  type: NodePort
