server:
    port: 8080
    context-path: /sbarnacle-studious-spoon
    servlet:
        contextPath: /sbarnacle-studious-spoon

spring:
    dataSource:
        driverClassName: 'org.postgresql.Driver'
        password: 'sbarnacle'
        sql-script-encoding: UTF-8
        url: 'jdbc:postgresql://postgres-sbrncl-svc.sbarnacle.svc.cluster.local:5432/sbarnacle'
        # set spring.dataSource.url=jdbc:postgresql://192.168.100.141:32671/sbarnacle
        username: 'sbarnacle'
    jpa:
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults:
                        false

                    
app:
    jwtExpirationInMs:
        604800000
    jwtSecret:
        myapp@uthk3y
    jwt_token_rca_public_key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3qhkuUYr27zrJvvD0PyK
        HTwO5OD+ImnWjUlZkDO1Ya76cbfu/FCU9dq0AGh2knzUDdNfIJsyBGroFPDeHZXj
        5Ho/vtt3hl6BUtwAR0KVJemF/tQO4pdhh5aboaLOvqFLHprAWJKSWku4MAcP8LXD
        RW364TdgWWX9wgSGhbSRhu/JDujv6e/Hfi42DagxwuGmkYTX5js4C4//otLt63dO
        JVROWmqp52tCmR5aDtybmlMH6DGAcNNwo74FnrCCiogx6b/ZqpQ11UUQEmpRdpME
        TgkrN1TQqGzS3J02U09g89wKciNNIOv2QNDuLZwmjr4jmeW+EIDcbOHPrMKO5ggC
        ZQIDAQAB
        -----END PUBLIC KEY-----

management:
    security:
        enabled: false

